{{- range $name := list "server" "worker" "broker" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Release.Name }}-{{ $name }}
  labels:
    {{- include "effect-agent.labels" $ | nindent 4 }}
  annotations:
    {{- toYaml (index $.Values.serviceAccount $name).annotations | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
